### ISSUE TITLE
Orion-Wilma

### ISSUE THREAD

**Issue by fernandorr21** [epam/Wilma#108]
hello, I would like to obtain in wilma the attributes of an entity already defined in orion based on its id. In order to evaluate those attributes in authzforce. Could it be done?

**Comment by tkohegyi** [comment]
Hi @fernandorr21 - to be honest I am not familiar with orion, but if it is about to implement orion message based content evaluation (condition in wilma, or interceptor in wilma), I believe it can be done. If you could explain the case in details, maybe I can help a bit more.
