### ISSUE TITLE
Mysterious duplicated files in search result zip

### ISSUE THREAD

**Issue by tibor-kovacs-epam** [epam/Wilma#21]
In the log I can see warnings logged about a couple of files (for example: Exception occurred while creating zip stream from file: 20150312162229.0006req.txt) even though these files can be found in the zip and they are readable.

Also these files seem to show up duplicated in the zip having a prefix of '1_ ' (example: 1_20150312162229.0006req.txt)

**Comment by tkohegyi** [comment]
not reproducible
