### ISSUE TITLE
Test-client test-server communication issue in performance mode

### ISSUE THREAD

**Issue by TiborKovacsEP** [epam/Wilma#31]
The communication between test-client and test-server is not stable in performance test mode. Because after some sent requests the client gets connection timeout httpcode and the responses don't arrive anymore.
"
09:57:10.288 [main] INFO  c.e.w.test.client.HttpRequestSender - status code: 200
09:57:10.308 [main] INFO  c.e.w.test.client.HttpRequestSender - status code: 200
09:57:10.328 [main] INFO  c.e.w.test.client.HttpRequestSender - status code: 200
09:57:10.338 [main] INFO  c.e.w.test.client.HttpRequestSender - status code: 200
09:57:10.358 [main] INFO  c.e.w.test.client.HttpRequestSender - status code: 200
09:57:10.368 [main] INFO  c.e.w.test.client.HttpRequestSender - status code: 200
09:57:30.401 [main] INFO  c.e.w.test.client.HttpRequestSender - status code: 504
..."
Extra enhancement:
It would be great if the Client got a mechanism to control the load.

**Comment by TiborKovacsEP** [comment]
The bug has resolved on the "testserver-testclient-highload-investigation" branch.
Review process has already finished.

**Comment by TiborKovacsEP** [comment]
The pull-request was accepted and merged to the master on Apr 18, so this bug is resolved.

**Comment by tkohegyi** [comment]
tested, bot the bug was fixed, and the enhancement (control the load) implemented
