### ISSUE TITLE
safety - low on thread situation handling

### ISSUE THREAD

**Issue by tkohegyi** [epam/Wilma#40]
```
01:07:44.649 [SocketListener0-254] INFO  n.l.b.p.jetty.http.SocketListener - LOW ON THREADS ((256-255+0)<2) on SocketListener0@0.0.0.0:9092
....
01:07:45.309 [SocketListener0-236] WARN  n.l.b.p.jetty.http.SocketListener - OUT OF THREADS: SocketListener0@0.0.0.0:9092
```
Investigate how Wilma behaves in case Jetty runs out of threads,

When this happens technically the message handling stops.

**Comment by TiborKovacsEP** [comment]
During safeguard action, the message logging actually not turned off properly, as the queue usage is not turned off (as it is expected), just there was a short-cut in onMessage handlings to make it much faster. Still was unable to handle problem in message queue itself.

**Comment by TiborKovacsEP** [comment]
This is bug, need to fix it by not sending messages to `loggerQueue` when msg logging turned off automatically.

**Comment by tkohegyi** [comment]
fix is in, testing...

**Comment by tkohegyi** [comment]
Addressed properly, available in next release.
