### ISSUE TITLE
release Wilma apps in Docker Hub too

### ISSUE THREAD

**Issue by tkohegyi** [epam/Wilma#61]
To provide help for people those would like to use Wilma in cloud, provide sample docker images

One image need for Wilma itself.
Another image need where Wilma and Wilma Message Search are working together.

**Comment by tkohegyi** [comment]
Initial versions (images) created and published at https://hub.docker.com/u/epam/ 
Wiki available: https://github.com/epam/Wilma/wiki/Docker-image-of-Wilma 
Still on docker branch, but soon to be merged to master.

**Comment by Maverick-Crank-GRey** [comment]
Can the "./start_wilma.sh" execution be added into the image init scripts?

**Comment by tkohegyi** [comment]
In short: Yes, it can be added.

Right now it is possible to update the configuration file and the start script before Wilma (or Wilma with Message Search) actually started. 
Therefore the start script execution can be added to the image, just need to keep/ensure proper configurability of Wilma/Wilma MS. 
Working on your proposal...

**Comment by tkohegyi** [comment]
https://docs.docker.com/userguide/dockervolumes/ will help us (even would offer to preserve the messages after the image stopped)

**Comment by tkohegyi** [comment]
https://github.com/epam/Wilma/commit/580bf18c0997dfaedd621fb9584568b9ab7e84a7

**Comment by tkohegyi** [comment]
Wiki page updated, thanks to Maverick-Crank-GRay for the suggestion. New images are available on Docker Hub.
Source is still on docker branch, if no further comment arrives, will be merged to master.

**Comment by tkohegyi** [comment]
Merged tp master, fell free to use.
