### ISSUE TITLE
Limit the message list in the Message log UI

### ISSUE THREAD

**Issue by tkohegyi** [epam/Wilma#7]
Right now we list all the existing messages at message log window, even if it is actually over 100k...
This sometimes to long and cause extra page load time.
Proposal:
- add `message.log.UI.maxsize=500` property
- at Wilma start load this parameter, it is a must have parameter
- when the list of messages are displayed on UI, show at most so many files in the list as specified in message.log.UI.maxsize parameter

**Comment by TiborKovacsEP** [comment]
Extra user expectation: if there are more message then the <maxsize> value, the last <maxsize> messages will be displayed.

**Comment by TiborKovacsEP** [comment]
Mr. boborjan,
I ask a review for 7-limit-message-list branch.

**Comment by boborjan** [comment]
Review items:
*buildMessageFileListJson*
I think it would be better if this method would only handle the creation of the *messageFiles* while the filtering and conversion to JSON would be handled by separate components.

**Comment by TiborKovacsEP** [comment]
I have separated the ways of creating result JSON from log files and message files. But I don't think this method should only handle the creation of the message files, because it's only a function call. And the filtering is just a check whether the result list has more elements than the limit or not.

**Comment by boborjan** [comment]
Okay.

**Comment by tkohegyi** [comment]
Fix merged. Minimum size of the list is 10. Wilma got new version (1.1) because introducing the new property value is not backward compatible.
