### ISSUE TITLE
Wilma:how to set headers in response

### ISSUE THREAD

**Issue by brijeshps** [epam/Wilma#84]
could you please help me with some examples for setting **headers** in response.

**Comment by tkohegyi** [comment]
Hi @brijeshps,  could you please give me some more context? Would you like to set headers in a stub response or when you use it as proxy? In case of stub response, which way you use to send the response back? I.e. do you use template file and template formatters or do you generate the response from scratch? These approaches offers different solutions.

**Comment by brijeshps** [comment]
Dear Tamás,
I would like to set headers in a stub response. I am using template file and template formatters.

**Comment by tkohegyi** [comment]
Hi @brijeshps, two ways are offered. 

1st option: Use built-in template formatter class: "HeaderFormatter", where param name is used as name of the header, value is used as value of the header, like:
```
<template-formatter class="HeaderFormatter">
	<param name="myHeaderName" value="myHeaderValue" />
	<param name="anotherHeaderName" value="anotherHeaderValue"/>
</template-formatter> 
```
The 2nd option is to write and use your own template formatter class, that sets/alters the response header as you would like to. You may use the source of "HeaderFormatter" class to see how it works. The class is at wilma-stub-configuration-support module and in package com.epam.wilma.stubconfig.template.formatter.

Please let me know if it helps, or you need more information.

**Comment by brijeshps** [comment]
Dear Tamás,
I have used the 2nd option and it worked. Thanks for your help.
