### ISSUE TITLE
Enhancement - replacing XML based stub configuration with JSON based stub configuration

### ISSUE THREAD

**Issue by tkohegyimsm** [epam/Wilma#88]
It is possible, since we have good json schema validation possibilities. Technically this enhancement would mean that Wilma jumps to its second generation (V2.x). So it is a huge rework.

**Comment by tkohegyi** [comment]
closed by accident - issue #94 is prepared the approach, now just need to implement it

**Comment by tkohegyi** [comment]
This is actualy done, code is on master (V2.x series of Wilma)
WHat is still missing - lots of tests before it is published officially...

**Comment by tkohegyi** [comment]
Wiki pages, docs updating is ongoing + test will be done after that.

**Comment by tkohegyi** [comment]
Published with V2.0.x release
